language: python
python:
  - "3.6"
  - "2.7"

install:
  - pip install -e .
  - pip install -r dev-requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - coverage run --source pywebostv -m py.test

after_success:
  - coveralls
